# Mandatory
server:
  port: 7000

# Mandatory.
cache:
  host: "localhost"
  port: 6379
  ttl: "PT10M"
  # Optional. Default is 0.
  db: 1

# Optional.
responseCache:
  mongoURL: "mongodb://tvast:password@localhost:27017/protocol_server-v2?authSource=admin"
  ttl: "PT10M"

# Mandatory.
# Priority order will be
# 1. Synchronous
# 2. webhook
# 3. pubSub
client:
  synchronous: 
    mongoURL: "mongodb://tvast:password@localhost:27017/protocol_server-v2?authSource=admin"

    # webhook:
      # url: "https://decentlogic-sb.loca.lt"
  
    #messageQueue: 
      # amqpURL: "amqp://guest:guest@localhost:5672"
      # incomingQueue: "protocol-server-incoming"
      # outgoingQueue: "protocol-server-outgoing"

# Mandatory.
app:
  # Mandatory.
  mode: bap

  # Two types of gateway mode present.
  # client and network.
  gateway:
    mode: network
    inboxQueue: "inbox-bap"
    outboxQueue: "outbox-bap"
    amqpURL: "amqp://tvast:password@localhost:5672"

  # Mandatory.
  actions:
    requests:
      search:
        ttl : "PT10S"
      init:
        ttl : "PT10S"
    
    responses: 
      on_search:
        ttl: "PT10S"
      
      on_init:
        ttl: "PT10S"
  
  # Mandatory.
  privateKey: "xkYBuOZiR0TtshEtMpohl6G+EwzRsZMjnXmb+EftLDh8KHPygRyWg8dQNzJ5ZqUFhRFnZqvN+UrEMS5yW3VW4Q=="
  publicKey: "fChz8oEcloPHUDcyeWalBYURZ2arzflKxDEuclt1VuE="

  # Mandatory.
  subscriberId: "dl-bap"
  subscriberUri: "https://decentlogic-bap.loca.lt"
  
  # Mandatory.
  registryUrl: https://registry.becknprotocol.io/subscribers
  auth: true
  uniqueKey: "dl-bap"
  
  # Mandatory.
  city: "std:080"
  country: "IND"

  # Mandatory.
  ttl: "PT10M"

  # Mandatory.
  httpTimeout: "PT3S"
  httpRetryCount: 2
  telemetry:
    enabled: false
    url: ""
    batchSize: 100
    # In minutes
    syncInterval: 30
    redis_db: 3
  
  useHMACForWebhook: false
  sharedKeyForWebhookHMAC: ""

  useLayer2Config: false
  mandateLayer2Config: false

  openAPIValidator:
    cachedFileLimit: 5
    initialFilesToCache: ""
